### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jdkato** [jdkato/prose#5]
This is rough outline of some improvements I'd like to make.

### Documentation

- [x] Improve and update README.
- [ ] Add [.github](https://github.com/blog/2111-issue-and-pull-request-templates) files.

### tokenize

- [x] Port the [pragmatic_segmenter](https://github.com/diasks2/pragmatic_segmenter).
- [x] Get `PunktSentenceTokenizer` passing the The Golden Rules and possibly submit a PR upstream.

### tag

- [x] Finish porting the `PerceptronTagger` (just training functionality left).
- [x] ~~Port the TnT Tagger~~ (not going to make v1.0).
- [ ] Improve testing strategy (we currently rely on NLTK).

### transform 

- [x] Improve `Title` and add support for variations (e.g., AP style).
- [ ] Port [Change Case](https://github.com/blakeembrey/change-case).

### summarize

- [x] Finish working on `Syllables`.
- [x] Add a composite "years-of-education" metric.
- [ ] Add the ability to update a `Document`'s content without having to recalculate all of its statistics.
- [x] Expand test suite.

**Comment by elliott5** [comment]
Are you planning to add an NP-Chunker to allow noun-phase extraction?

I've knocked-up a very simple proper-name extractor in Go, using the output of ```package tag```, but I feel sure there must be something more elegant out there to work from. For example: https://github.com/lukewrites/NP_chunking_with_nltk/blob/master/NP_chunking_with_the_NLTK.ipynb

**Comment by jdkato** [comment]
I'm certainly not against it, but I can't say how soon I'd get around to it either. My priorities at the moment are roughly:

1. Finish what I've started working (mostly the stuff listed above minus the `pragmatic_segmenter` and the TnT tagger, which are more long-term goals);
2. improve the test suite for existing functionality; and then
3.  add new functionality.

Of course, I'm open to PRs as well.

**Comment by moorereason** [comment]
Regarding the Change Case item, you could also look into https://github.com/markbates/inflect.

**Comment by jdkato** [comment]
Thanks for the tip&mdash;that looks like a useful package.

**Comment by jdkato** [comment]
I'm going to consider this closed.

The next stage in prose's development, as far as I'm concerned, is becoming multilingual.  I have a number of ideas about how to approach this, but I'm leaning towards supporting [spaCy's models](https://github.com/explosion/spacy-models). License-wise, this should be fine since they're all released under CC BY-SA 3.0.

This will likely require a major refactor but the opportunity to bring top-tier NLP to Go makes it worthwhile, IMO.
